#!/usr/bin/env bash
set -Eeuo pipefail
set +x

log() { printf '[default-privileges-isolated] %s\n' "$*"; }
fail() { printf '[default-privileges-isolated] ERROR: %s\n' "$*" >&2; exit 1; }
psql_local() { psql -X --no-psqlrc -v ON_ERROR_STOP=1 "$@"; }
public_exec_acl() {
  local signature="$1"
  psql_local -qAt -c "
    select coalesce(bool_or(x.grantee = 0 and x.privilege_type = 'EXECUTE'), false)::text
    from pg_proc p
    left join lateral aclexplode(p.proacl) x on true
    where p.oid = '$signature'::regprocedure;
  " | tr -d '[:space:]'
}

command -v psql >/dev/null 2>&1 || fail 'psql is required'

# Snapshot existing intentional-public ACLs. ALTER DEFAULT PRIVILEGES affects only
# future objects; these four current explicit public objects must remain unchanged.
public_before="$(psql_local -qAt -c "
  select string_agg(concat(c.relname, ':', coalesce(c.relacl::text,'')), '|' order by c.relname)
  from pg_class c join pg_namespace n on n.oid=c.relnamespace
  where n.nspname='public' and c.relname in ('series_lineup','series_price_history','series_restock_info','series_stock_reports');
")"

# Current local Supabase already uses safer defaults, while read-only Production
# inspection on 2026-09-04 showed the legacy existing-project defaults below for
# owner role postgres. Reproduce that exact Production-like starting condition only
# inside this disposable DB before testing the official hardening candidate.
psql_local -q >/dev/null <<'SQL'
alter default privileges for role postgres in schema public
  grant all privileges on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant all privileges on functions to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant all privileges on sequences to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public;
SQL

# Baseline probes must now reproduce Production behavior for future postgres-owned
# public objects. Probes are disposable and immediately removed.
psql_local -q >/dev/null <<'SQL'
create table public.__default_acl_before(id bigint generated by default as identity primary key, value text);
create function public.__default_fn_before() returns integer language sql as $$ select 1 $$;
SQL
for role in anon authenticated service_role; do
  [[ "$(psql_local -qAt -c "select has_table_privilege('$role','public.__default_acl_before','SELECT,INSERT,UPDATE,DELETE');" | tr -d '[:space:]')" == 't' ]] || fail "Production-like table CRUD auto-grant missing for $role"
  [[ "$(psql_local -qAt -c "select has_function_privilege('$role','public.__default_fn_before()','EXECUTE');" | tr -d '[:space:]')" == 't' ]] || fail "Production-like function EXECUTE auto-grant missing for $role"
  seq_before="$(psql_local -qAt -c "select pg_get_serial_sequence('public.__default_acl_before','id');" | tr -d '[:space:]')"
  [[ "$(psql_local -qAt -c "select has_sequence_privilege('$role','$seq_before','USAGE,SELECT');" | tr -d '[:space:]')" == 't' ]] || fail "Production-like sequence access missing for $role"
done
[[ "$(public_exec_acl 'public.__default_fn_before()')" == 'false' ]] || fail 'Production-like baseline unexpectedly grants function EXECUTE to PUBLIC ACL'
psql_local -q -c 'drop function public.__default_fn_before(); drop table public.__default_acl_before;' >/dev/null
log 'Exact observed Production-style postgres default ACL reproduced in disposable DB'

# Candidate: exact current Supabase "Securing your API" opt-in guidance for role postgres.
# This changes defaults for future objects only; existing objects are untouched.
psql_local -q >/dev/null <<'SQL'
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public;
SQL

psql_local -q >/dev/null <<'SQL'
create table public.__default_acl_hardened(id bigint generated by default as identity primary key, value text);
create function public.__default_fn_hardened() returns integer language sql as $$ select 1 $$;
SQL
for role in anon authenticated service_role; do
  [[ "$(psql_local -qAt -c "select has_table_privilege('$role','public.__default_acl_hardened','SELECT');" | tr -d '[:space:]')" == 'f' ]] || fail "future table SELECT remained auto-granted to $role"
  [[ "$(psql_local -qAt -c "select has_table_privilege('$role','public.__default_acl_hardened','INSERT');" | tr -d '[:space:]')" == 'f' ]] || fail "future table INSERT remained auto-granted to $role"
  [[ "$(psql_local -qAt -c "select has_table_privilege('$role','public.__default_acl_hardened','UPDATE');" | tr -d '[:space:]')" == 'f' ]] || fail "future table UPDATE remained auto-granted to $role"
  [[ "$(psql_local -qAt -c "select has_table_privilege('$role','public.__default_acl_hardened','DELETE');" | tr -d '[:space:]')" == 'f' ]] || fail "future table DELETE remained auto-granted to $role"
  [[ "$(psql_local -qAt -c "select has_function_privilege('$role','public.__default_fn_hardened()','EXECUTE');" | tr -d '[:space:]')" == 'f' ]] || fail "future function EXECUTE remained auto-granted to $role"
done
[[ "$(public_exec_acl 'public.__default_fn_hardened()')" == 'false' ]] || fail 'future function EXECUTE remained granted to PUBLIC ACL'

seq_name="$(psql_local -qAt -c "select pg_get_serial_sequence('public.__default_acl_hardened','id');" | tr -d '[:space:]')"
[[ -n "$seq_name" ]] || fail 'identity sequence not found'
for role in anon authenticated service_role; do
  [[ "$(psql_local -qAt -c "select has_sequence_privilege('$role','$seq_name','USAGE');" | tr -d '[:space:]')" == 'f' ]] || fail "future sequence USAGE remained auto-granted to $role"
  [[ "$(psql_local -qAt -c "select has_sequence_privilege('$role','$seq_name','SELECT');" | tr -d '[:space:]')" == 'f' ]] || fail "future sequence SELECT remained auto-granted to $role"
done

# Explicit allowlist still works after hardening: service-role-only server table plus
# one intentional public read table can be granted deliberately.
psql_local -q >/dev/null <<'SQL'
grant select, insert, update, delete on public.__default_acl_hardened to service_role;
grant usage, select on sequence public.__default_acl_hardened_id_seq to service_role;
create table public.__default_public_probe(id integer primary key, value text not null);
alter table public.__default_public_probe enable row level security;
create policy "explicit public read" on public.__default_public_probe for select to anon using (true);
grant select on public.__default_public_probe to anon;
insert into public.__default_public_probe values (1,'ok');
SQL
[[ "$(psql_local -qAt <<'SQL' | tail -n 1 | tr -d '[:space:]'
set role anon;
select value from public.__default_public_probe where id=1;
SQL
)" == 'ok' ]] || fail 'explicit intentional-public grant failed after default hardening'

public_after="$(psql_local -qAt -c "
  select string_agg(concat(c.relname, ':', coalesce(c.relacl::text,'')), '|' order by c.relname)
  from pg_class c join pg_namespace n on n.oid=c.relnamespace
  where n.nspname='public' and c.relname in ('series_lineup','series_price_history','series_restock_info','series_stock_reports');
")"
[[ "$public_before" == "$public_after" ]] || fail 'existing intentional-public ACLs changed unexpectedly'
log 'FORWARD PASS: future Data API exposure is opt-in while explicit grants and current public ACLs remain valid'

# Remove forward probes before rollback rehearsal.
psql_local -q -c 'drop table public.__default_public_probe; drop function public.__default_fn_hardened(); drop table public.__default_acl_hardened;' >/dev/null

# Restore the exact observed Production-style postgres defaults as rollback proof.
psql_local -q >/dev/null <<'SQL'
alter default privileges for role postgres in schema public
  grant all privileges on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant all privileges on functions to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant all privileges on sequences to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public;
SQL
psql_local -q >/dev/null <<'SQL'
create table public.__default_acl_rollback(id bigint generated by default as identity primary key, value text);
create function public.__default_fn_rollback() returns integer language sql as $$ select 1 $$;
SQL
rollback_seq="$(psql_local -qAt -c "select pg_get_serial_sequence('public.__default_acl_rollback','id');" | tr -d '[:space:]')"
for role in anon authenticated service_role; do
  [[ "$(psql_local -qAt -c "select has_table_privilege('$role','public.__default_acl_rollback','SELECT,INSERT,UPDATE,DELETE');" | tr -d '[:space:]')" == 't' ]] || fail "rollback did not restore table CRUD auto-grant for $role"
  [[ "$(psql_local -qAt -c "select has_function_privilege('$role','public.__default_fn_rollback()','EXECUTE');" | tr -d '[:space:]')" == 't' ]] || fail "rollback did not restore function EXECUTE for $role"
  [[ "$(psql_local -qAt -c "select has_sequence_privilege('$role','$rollback_seq','USAGE,SELECT');" | tr -d '[:space:]')" == 't' ]] || fail "rollback did not restore sequence access for $role"
done
[[ "$(public_exec_acl 'public.__default_fn_rollback()')" == 'false' ]] || fail 'rollback did not restore Production-like PUBLIC function denial in ACL'
psql_local -q -c 'drop function public.__default_fn_rollback(); drop table public.__default_acl_rollback;' >/dev/null
log 'ROLLBACK PASS: exact Production-style auto-grant behavior restored'

# Reapply hardened desired end state and prove once more with fresh objects.
psql_local -q >/dev/null <<'SQL'
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from public;
create table public.__default_acl_final(id integer primary key, value text);
create function public.__default_fn_final() returns integer language sql as $$ select 1 $$;
SQL
for role in anon authenticated service_role; do
  [[ "$(psql_local -qAt -c "select has_table_privilege('$role','public.__default_acl_final','SELECT');" | tr -d '[:space:]')" == 'f' ]] || fail "final table reapply failed for $role"
  [[ "$(psql_local -qAt -c "select has_function_privilege('$role','public.__default_fn_final()','EXECUTE');" | tr -d '[:space:]')" == 'f' ]] || fail "final function reapply failed for $role"
done
[[ "$(public_exec_acl 'public.__default_fn_final()')" == 'false' ]] || fail 'final function reapply left PUBLIC EXECUTE in ACL'
psql_local -q -c 'drop function public.__default_fn_final(); drop table public.__default_acl_final;' >/dev/null

log 'PASS: exact Production baseline -> official hardening -> explicit allowlist -> rollback -> reapply verified'
