#!/usr/bin/env bash
set -Eeuo pipefail
set +x

log() { printf '[default-privileges-isolated] %s\n' "$*"; }
fail() { printf '[default-privileges-isolated] ERROR: %s\n' "$*" >&2; exit 1; }
psql_local() { psql -X --no-psqlrc -v ON_ERROR_STOP=1 "$@"; }
function_acl_has_grantee() {
  local signature="$1"
  local grantee="$2"
  psql_local -qAt -c "
    select coalesce(bool_or(
      x.privilege_type='EXECUTE'
      and x.grantee = case when '$grantee'='PUBLIC' then 0 else (select oid from pg_roles where rolname='$grantee') end
    ), false)::text
    from pg_proc p
    left join lateral aclexplode(coalesce(p.proacl, acldefault('f', p.proowner))) x on true
    where p.oid = '$signature'::regprocedure;
  " | tr -d '[:space:]'
}

command -v psql >/dev/null 2>&1 || fail 'psql is required'

public_before="$(psql_local -qAt -c "
  select string_agg(concat(c.relname, ':', coalesce(c.relacl::text,'')), '|' order by c.relname)
  from pg_class c join pg_namespace n on n.oid=c.relnamespace
  where n.nspname='public' and c.relname in ('series_lineup','series_price_history','series_restock_info','series_stock_reports');
")"

# Reproduce the read-only-observed Production schema-scoped postgres defaults.
# Do NOT alter the global hard-wired PUBLIC function default in this baseline.
psql_local -q >/dev/null <<'SQL'
alter default privileges for role postgres in schema public
  grant all privileges on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant all privileges on functions to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant all privileges on sequences to anon, authenticated, service_role;
SQL

psql_local -q >/dev/null <<'SQL'
create table public.__default_acl_before(id bigint generated by default as identity primary key, value text);
create function public.__default_fn_before() returns integer language sql as $$ select 1 $$;
SQL
seq_before="$(psql_local -qAt -c "select pg_get_serial_sequence('public.__default_acl_before','id');" | tr -d '[:space:]')"
for role in anon authenticated service_role; do
  [[ "$(psql_local -qAt -c "select has_table_privilege('$role','public.__default_acl_before','SELECT,INSERT,UPDATE,DELETE');" | tr -d '[:space:]')" == 't' ]] || fail "Production-like table CRUD auto-grant missing for $role"
  [[ "$(function_acl_has_grantee 'public.__default_fn_before()' "$role")" == 'true' ]] || fail "Production-like direct function EXECUTE grant missing for $role"
  [[ "$(psql_local -qAt -c "select has_sequence_privilege('$role','$seq_before','USAGE,SELECT');" | tr -d '[:space:]')" == 't' ]] || fail "Production-like sequence access missing for $role"
done
[[ "$(function_acl_has_grantee 'public.__default_fn_before()' 'PUBLIC')" == 'true' ]] || fail 'expected PostgreSQL hard-wired PUBLIC function EXECUTE was not present'
psql_local -q -c 'drop function public.__default_fn_before(); drop table public.__default_acl_before;' >/dev/null
log 'Production-like schema grants plus PostgreSQL hard-wired PUBLIC EXECUTE reproduced'

# Candidate A: stop automatic Data API role grants in public. This is schema-scoped
# and does not attempt to change PostgreSQL's global PUBLIC function default.
psql_local -q >/dev/null <<'SQL'
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;
SQL

psql_local -q >/dev/null <<'SQL'
create table public.__default_acl_hardened(id bigint generated by default as identity primary key, value text);
create function public.__default_fn_hardened() returns integer language sql as $$ select 1 $$;
SQL
seq_name="$(psql_local -qAt -c "select pg_get_serial_sequence('public.__default_acl_hardened','id');" | tr -d '[:space:]')"
for role in anon authenticated service_role; do
  for privilege in SELECT INSERT UPDATE DELETE; do
    [[ "$(psql_local -qAt -c "select has_table_privilege('$role','public.__default_acl_hardened','$privilege');" | tr -d '[:space:]')" == 'f' ]] || fail "future table $privilege remained auto-granted to $role"
  done
  [[ "$(function_acl_has_grantee 'public.__default_fn_hardened()' "$role")" == 'false' ]] || fail "future function retained direct EXECUTE ACL for $role"
  [[ "$(psql_local -qAt -c "select has_sequence_privilege('$role','$seq_name','USAGE');" | tr -d '[:space:]')" == 'f' ]] || fail "future sequence USAGE remained auto-granted to $role"
  [[ "$(psql_local -qAt -c "select has_sequence_privilege('$role','$seq_name','SELECT');" | tr -d '[:space:]')" == 'f' ]] || fail "future sequence SELECT remained auto-granted to $role"
done
[[ "$(function_acl_has_grantee 'public.__default_fn_hardened()' 'PUBLIC')" == 'true' ]] || fail 'schema-scoped hardening unexpectedly changed global PUBLIC function default'
[[ "$(psql_local -qAt -c "select has_function_privilege('anon','public.__default_fn_hardened()','EXECUTE');" | tr -d '[:space:]')" == 't' ]] || fail 'expected effective anon EXECUTE through PUBLIC was not reproduced'
log 'SCHEMA HARDENING PASS: table/sequence and direct API-role defaults removed; PUBLIC function caveat reproduced'

# Explicit grants still work after Candidate A.
psql_local -q >/dev/null <<'SQL'
grant select, insert, update, delete on public.__default_acl_hardened to service_role;
grant usage, select on sequence public.__default_acl_hardened_id_seq to service_role;
revoke execute on function public.__default_fn_hardened() from public;
grant execute on function public.__default_fn_hardened() to service_role;
create table public.__default_public_probe(id integer primary key, value text not null);
alter table public.__default_public_probe enable row level security;
create policy "explicit public read" on public.__default_public_probe for select to anon using (true);
grant select on public.__default_public_probe to anon;
insert into public.__default_public_probe values (1,'ok');
SQL
[[ "$(psql_local -qAt -c "select has_function_privilege('service_role','public.__default_fn_hardened()','EXECUTE');" | tr -d '[:space:]')" == 't' ]] || fail 'explicit service-role function grant failed'
[[ "$(psql_local -qAt -c "select has_function_privilege('anon','public.__default_fn_hardened()','EXECUTE');" | tr -d '[:space:]')" == 'f' ]] || fail 'explicit per-function PUBLIC revoke failed to protect anon'
[[ "$(psql_local -qAt <<'SQL' | tail -n 1 | tr -d '[:space:]'
set role anon;
select value from public.__default_public_probe where id=1;
SQL
)" == 'ok' ]] || fail 'explicit intentional-public table grant failed'

public_after="$(psql_local -qAt -c "
  select string_agg(concat(c.relname, ':', coalesce(c.relacl::text,'')), '|' order by c.relname)
  from pg_class c join pg_namespace n on n.oid=c.relnamespace
  where n.nspname='public' and c.relname in ('series_lineup','series_price_history','series_restock_info','series_stock_reports');
")"
[[ "$public_before" == "$public_after" ]] || fail 'existing intentional-public ACLs changed unexpectedly'

# Candidate B blast-radius rehearsal only: PostgreSQL requires a GLOBAL default
# revoke to remove hard-wired PUBLIC EXECUTE from future functions. Prove both the
# desired public effect and the broader all-schema effect; this is not automatically
# selected for Production.
psql_local -q >/dev/null <<'SQL'
alter default privileges for role postgres revoke execute on functions from public;
create function public.__default_fn_global_hardened() returns integer language sql as $$ select 1 $$;
create function extensions.__default_fn_global_scope_probe() returns integer language sql as $$ select 1 $$;
SQL
[[ "$(function_acl_has_grantee 'public.__default_fn_global_hardened()' 'PUBLIC')" == 'false' ]] || fail 'global PUBLIC revoke failed for future public function'
[[ "$(function_acl_has_grantee 'extensions.__default_fn_global_scope_probe()' 'PUBLIC')" == 'false' ]] || fail 'global PUBLIC revoke did not demonstrate all-schema scope'
[[ "$(psql_local -qAt -c "select has_function_privilege('anon','public.__default_fn_global_hardened()','EXECUTE');" | tr -d '[:space:]')" == 'f' ]] || fail 'global PUBLIC revoke did not remove effective anon execution'
log 'GLOBAL OPTION PASS: PUBLIC function default can be removed, and all-schema blast radius is proven'

# Clean probes, then rehearse rollback to the observed Production schema grants and
# PostgreSQL hard-wired PUBLIC function behavior.
psql_local -q >/dev/null <<'SQL'
drop function extensions.__default_fn_global_scope_probe();
drop function public.__default_fn_global_hardened();
drop table public.__default_public_probe;
drop function public.__default_fn_hardened();
drop table public.__default_acl_hardened;
alter default privileges for role postgres grant execute on functions to public;
alter default privileges for role postgres in schema public
  grant all privileges on tables to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant all privileges on functions to anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  grant all privileges on sequences to anon, authenticated, service_role;
create table public.__default_acl_rollback(id bigint generated by default as identity primary key, value text);
create function public.__default_fn_rollback() returns integer language sql as $$ select 1 $$;
SQL
rollback_seq="$(psql_local -qAt -c "select pg_get_serial_sequence('public.__default_acl_rollback','id');" | tr -d '[:space:]')"
for role in anon authenticated service_role; do
  [[ "$(psql_local -qAt -c "select has_table_privilege('$role','public.__default_acl_rollback','SELECT,INSERT,UPDATE,DELETE');" | tr -d '[:space:]')" == 't' ]] || fail "rollback did not restore table CRUD auto-grant for $role"
  [[ "$(function_acl_has_grantee 'public.__default_fn_rollback()' "$role")" == 'true' ]] || fail "rollback did not restore direct function EXECUTE for $role"
  [[ "$(psql_local -qAt -c "select has_sequence_privilege('$role','$rollback_seq','USAGE,SELECT');" | tr -d '[:space:]')" == 't' ]] || fail "rollback did not restore sequence access for $role"
done
[[ "$(function_acl_has_grantee 'public.__default_fn_rollback()' 'PUBLIC')" == 'true' ]] || fail 'rollback did not restore hard-wired PUBLIC function behavior'
psql_local -q -c 'drop function public.__default_fn_rollback(); drop table public.__default_acl_rollback;' >/dev/null
log 'ROLLBACK PASS: Production-style schema grants and PUBLIC function behavior restored'

# Final isolated end state: Candidate A only. Candidate B remains a separately
# classified option because it changes future postgres-owned functions in every schema.
psql_local -q >/dev/null <<'SQL'
alter default privileges for role postgres in schema public
  revoke select, insert, update, delete on tables from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke execute on functions from anon, authenticated, service_role;
alter default privileges for role postgres in schema public
  revoke usage, select on sequences from anon, authenticated, service_role;
create table public.__default_acl_final(id integer primary key, value text);
create function public.__default_fn_final() returns integer language sql as $$ select 1 $$;
SQL
for role in anon authenticated service_role; do
  [[ "$(psql_local -qAt -c "select has_table_privilege('$role','public.__default_acl_final','SELECT');" | tr -d '[:space:]')" == 'f' ]] || fail "final table hardening failed for $role"
  [[ "$(function_acl_has_grantee 'public.__default_fn_final()' "$role")" == 'false' ]] || fail "final direct function ACL hardening failed for $role"
done
[[ "$(function_acl_has_grantee 'public.__default_fn_final()' 'PUBLIC')" == 'true' ]] || fail 'final state should preserve global PUBLIC default until separately approved'
psql_local -q -c 'drop function public.__default_fn_final(); drop table public.__default_acl_final;' >/dev/null

log 'PASS: schema-role hardening, explicit function protection, global blast-radius proof, rollback, and Candidate-A reapply verified'
